version: '3.9'

services:
  cmcintel-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: cmcintel-frontend:latest
    container_name: cmcintel-frontend
    ports:
      - "3000:80"
    restart: always
